name: "lw-scanner"
description: "Scan container images for vulnerabilities with Lacework's Inline Scanner"
author: "Lacework"
inputs:
  LW_ACCOUNT_NAME:
    description: "Your Lacework account name. For example, if your login URL is mycompany.lacework.net, the account name is mycompany."
    required: true
  LW_ACCESS_TOKEN:
    description: "Authorization token. Copy and paste the token from the inline scanner integration created in the Lacework console."
    required: true
  IMAGE_NAME:
    description: "Name of the container image you want to scan, for example, `node`."
    required: true
  IMAGE_TAG:
    description: "Tag of the container image you want to scan, for example, `12.18.2-alpine`."
    required: true
  SCAN_LIBRARY_PACKAGES:
    description: "Also scan software packages. (Default: true)"
    required: false
    default: "true"
  SAVE_RESULTS_IN_LACEWORK:
    description: "Save results to Lacework. (Default: false)"
    required: false
    default: "false"
  SAVE_BUILD_REPORT:
    description: "Saves the evaluation report as a local HTML file. (Default: false)"
    required: false
    default: "false"
  BUILD_REPORT_FILE_NAME:
    description: "Specify custom file name for the HTML evalutation report, by default the name is OS_TYPE-IMAGE_DIGEST_SHA256.html."
    required: false
runs:
  using: "docker"
  image: "docker://docker.io/lacework/lw-scanner-image:latest"
  args:
    - ${{ inputs.LW_ACCOUNT_NAME }}
    - ${{ inputs.LW_ACCESS_TOKEN }}
    - ${{ inputs.IMAGE_NAME }}
    - ${{ inputs.IMAGE_TAG }}
    - ${{ inputs.SCAN_LIBRARY_PACKAGES }}
    - ${{ inputs.SAVE_RESULTS_IN_LACEWORK }}
    - ${{ inputs.SAVE_BUILD_REPORT }}
    - ${{ inputs.BUILD_REPORT_FILE_NAME }}
branding:
  icon: "alert-triangle"
  color: "blue"
