name: test-action-failure-fixable
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "30 8 * * *"

jobs:
  test-action-failure-fixable:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker image pull ghcr.io/timarenz/vulnerable-container:v0.0.1

      - name: lw-scanner
        id: lw-scanner
        uses: ./
        continue-on-error: true
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: ghcr.io/timarenz/vulnerable-container
          IMAGE_TAG: v0.0.1
          SAVE_BUILD_REPORT: true
          BUILD_REPORT_FILE_NAME: report.html
          FAIL_BUILD: true
          SEVERITY_THRESHOLD: fixable

      - name: Check if action failed for any other reason then vulnerabilities found.
        if: steps.lw-scanner.outputs.EXIT_CODE != '1'
        run: echo "Action failed." && exit 1

      - name: Check if vulnerabilites were found and step failed.
        if: steps.lw-scanner.outputs.EXIT_CODE == '1'
        run: echo "Vulnerabilities found and step failed succesfully." && exit 0
